/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OAw1sZgYZq8
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export function CardsAutos() {
  return (
    (<div className="grid md:grid-cols-2 xl:grid-cols-4 gap-6">
      <Card>
        <CardHeader className="pb-4">
          <CardTitle className="text-2xl">ABC-1234</CardTitle>
          <CardDescription>License Plate</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-4">
          <p className="text-sm font-semibold">Model: Sedan</p>
          <p className="text-sm font-semibold">Issue: Oil Change</p>
          <p className="text-sm font-semibold">Client: John Doe</p>
        </CardContent>
      </Card>
      <Card>
        <CardHeader className="pb-4">
          <CardTitle className="text-2xl">DEF-5678</CardTitle>
          <CardDescription>License Plate</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-4">
          <p className="text-sm font-semibold">Model: Hatchback</p>
          <p className="text-sm font-semibold">Issue: Brake Service</p>
          <p className="text-sm font-semibold">Client: Alice Smith</p>
        </CardContent>
      </Card>
      <Card>
        <CardHeader className="pb-4">
          <CardTitle className="text-2xl">GHI-9101</CardTitle>
          <CardDescription>License Plate</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-4">
          <p className="text-sm font-semibold">Model: SUV</p>
          <p className="text-sm font-semibold">Issue: Tire Replacement</p>
          <p className="text-sm font-semibold">Client: Bob Johnson</p>
        </CardContent>
      </Card>
      <Card>
        <CardHeader className="pb-4">
          <CardTitle className="text-2xl">JKL-2345</CardTitle>
          <CardDescription>License Plate</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-4">
          <p className="text-sm font-semibold">Model: Convertible</p>
          <p className="text-sm font-semibold">Issue: Engine Check</p>
          <p className="text-sm font-semibold">Client: Emma Brown</p>
        </CardContent>
      </Card>
    </div>)
  );
}
