import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/component/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-400">
        <Sidebar></Sidebar>{children}</body>
    </html>
  );
}
